name: Simple
on: push
jobs:
  ubuntu :
  	runs-on: ubuntu-latest
	steps :
	 -run: date
   windowOld :
	runs-on: ubuntu-latest
	steps:
	 -run: date
   macos:
	needs:[ ubuntu, windows]
	runs-on: macos-latest
	steps:
	 -run: date
   depends :
	runs-on: macos-latest
	steps:
	 -run: date
